---
title: ""
sidebar: false
---

# STAT 312. Basic Statistics for Engineering and Science  
Case Western Reserve University, Fall 2026

Welcome to the world of Statistics! Statistics is not just about theories & numbers — it’s about making sense of the world.  

::: {.callout-tip title="📖 A Thought from H. G. Wells"}  
> “Statistical thinking will one day be as necessary for efficient citizenship as the ability to read and write.”  
:::  



**Instructor:** Md Mutasim Billah <br> **Class meeting times:**

-   **Section 103**: M/W/F 10:25-11:15am, White Building 411
-   **Section 104**: M/W/F 11:30-12:20pm, White Building 411
-   **Section 105**: M/W/F 02:05-02:55pm, Nord Hall 410

**Instructor's drop-in (office) hours:**

-   **Location:** My office (Sears 569)
-   **Times:** M/W: 1:00 - 1:30pm and 3 - 4:30pm
-   **Email Response Time:** I do my best to reply to emails promptly during weekdays. Please note that messages sent after 4:00 pm or on weekends may take longer to receive a response.




------------------------------------------------------------------------

This course website will be updated throughout the semester with new activities, assignments, schedule, etc so please bookmark this page if you are enrolled in the course!


If you find any typos, bugs, dead links, or have other questions, please email [mdmutasim.billah@case.edu](mailto:mdmutasim.billah@case.edu){.email}
