---
title: "Unit 06: Normal Distribution & Central Limit Theorem"
subtitle: "Instructor: Dr. Md Mutasim Billah"

format:
  html:
    embed-resources: true
    toc: true

  pptx:
    slide-level: 2
    reference-doc: ../master-cwru.pptx
    
format-links: false
---


```{r setup}
#| include: false
knitr::opts_chunk$set(
  collapse = TRUE, 
  warning = FALSE,
  message = FALSE,
  error = TRUE,
  fig.height = 2.75, 
  fig.width = 4.25,
  fig.env = 'figure',
  fig.pos = 'h',
  fig.align = 'center')
```


# Resources


## Handouts {-}

::: {.incremental}

- Download the [Unit 06 Handout: Normal Distribution & CTL](/handout/Unit-06-Normal-CTL.pdf) before class and bring it with you.

- In the class I have provided a copy of [Tables 1](/handout/Tables-1.pdf). If you have missed the class, meet me after the class or in mu OH to get a copy of the tables.

- I will continue to post additional handouts as we progress through the course. Please watch for **Canvas Announcements** when a new handout becomes available.

- It is very important that you **bring the appropriate handout to class regularly**, either as a printed copy or on your writing device.

:::



## Lecture Notes {-}

::: {.incremental}

- Download the [Lecture Notes Unit 06A: Normal Distribution](/handout/Unit-06A-Normal.pdf) and [Lecture Notes Unit 06B: Central Limit Theorem](/handout/Unit-06B-CLT.pdf) -- review the covered topics thoroughly after class. These lecture notes provide a more detailed and elaborated version of the material covered during class.

- For units where Lecture Notes/Handouts are provided, they should serve as one of your core course resources. For these units, you are not expected to use the textbook as your primary study resource, but feel free to go through the related topics in the textbooks (mentioned in the class) if you want to!

- You do not need to print the lecture notes or bring a printed copy to class. Save the printing money and buy yourself a treat instead! :)

-When lecture notes are available, please follow this order when studying:

  - Class Notes/Handouts: Your primary resource. These reflect exactly what we discuss, emphasize, and use in class.

  - Lecture Notes: Your main supplementary (required) resource. Use these for additional explanations, details, examples, and review after class.

  - Textbook: Use it when you would like to go through some additional (optional) resource.

Always prioritize the Class Notes if you notice any difference in notation, terminology, approach, or emphasis between the Class Notes and the Lecture Notes. Occasionally, I may present a concept or use notation slightly differently in class. I will also do my best to point out any important discrepancies as we move through the semester.



:::


## Practice Problems {-}

::: {.incremental}

- **Practice Problems (PP)** are essential for strengthening your understanding, building confidence, and exploring the concepts covered in class.

- The **Unit 06 Practice Problems** will be posted soon

- Complete the relevant Practice Problems as we progress through the unit.

- Make sure you have completed and reviewed the Practice Problems **before attempting the corresponding HW assignment**.

:::


