---
title: "Unit 04: Discrete Random Variable"
subtitle: "Instructor: Dr. Md Mutasim Billah"

format:
  html:
    embed-resources: true
    toc: true

  pptx:
    slide-level: 2
    reference-doc: ../master-cwru.pptx
    
format-links: false
---


```{r setup}
#| include: false
knitr::opts_chunk$set(
  collapse = TRUE, 
  warning = FALSE,
  message = FALSE,
  error = TRUE,
  fig.height = 2.75, 
  fig.width = 4.25,
  fig.env = 'figure',
  fig.pos = 'h',
  fig.align = 'center')
```


# Resources


## Handouts {-}

::: {.incremental}

- Download the [Unit 04 Handout: Probability](/handout/Unit-04-Discrete.pdf) before class and bring it with you.

- I will continue to post additional handouts as we progress through the course. Please watch for **Canvas Announcements** when a new handout becomes available.

- It is very important that you **bring the appropriate handout to class regularly**, either as a printed copy or on your writing device.

:::




## Practice Problems {-}

::: {.incremental}

- **Practice Problems (PP)** are essential for strengthening your understanding, building confidence, and exploring the concepts covered in class.

- The **Unit 03 Practice Problems** are available under the **Practice Problems** tab on the course website. The solutions are provided in Canvas.

- Complete the relevant Practice Problems as we progress through the unit.

- Make sure you have completed and reviewed the Practice Problems **before attempting the corresponding HW assignment**.

:::






# Probability


## Class Notes {-}

- Live class lecture notes
- I usually post the class notes on Canvas by the end of the day. If you don't see it, shoot me an email next day!


## Hypergeometric Distribution {-}

::: {.incremental}

- A set of $N$ objects contains:
  - $K$ objects classified as **successes**
  - $N-K$ objects classified as **failures**

- A sample of size $n$ is selected randomly **without replacement** from the $N$ objects, where $K\leq N$ and $n\leq N$.

- Let the random variable $X$ denote the **number of successes in the sample**.

- Then $X$ is a hypergeometric random variable with probability mass function

$$
P(X=x)
=
\frac{\binom{K}{x}\binom{N-K}{n-x}}
{\binom{N}{n}},
$$

where

$$
x=\max(0,n+K-N),\ldots,\min(K,n).
$$

:::




## Hypergeometric Mean and Variance {-}

::: {.incremental}

- If $X$ is a hypergeometric random variable with parameters $N$, $K$, and $n$, then

$$
\mu=E(X)=np,
$$

and

$$
\sigma^2=V(X)
=
np(1-p)
\left(
\frac{N-n}{N-1}
\right),
$$

where

$$
p=\frac{K}{N}.
$$

- The quantity

$$
\frac{N-n}{N-1}
$$

is called the **finite population correction factor**.

- Therefore,

$$
\sigma
=
\sqrt{
np(1-p)
\left(
\frac{N-n}{N-1}
\right)
}.
$$

- As the sampling fraction $n/N$ becomes small, the hypergeometric variance approaches the corresponding **binomial variance**.

:::